stages:
  data_ingestion:
    cmd: python -m src.data_ingestion
    deps:
      - src/data_ingestion.py
      - params.yaml
    outs:
      - data/raw/raw_data.csv
      - data/raw/X_train.csv
      - data/raw/X_test.csv

  data_preprocessing:
    cmd: python -m src.data_preprocessing
    deps:
      - src/data_preprocessing.py
      - data/raw/X_train.csv
      - data/raw/X_test.csv
      - params.yaml
    outs:
      - data/processed/train.npy
      - data/processed/test.npy
      - artifacts/preprocessor/preprocessor.pkl

  model_trainer:
    cmd: python -m src.model_trainer
    deps:
      - src/model_trainer.py
      - data/processed/train.npy
      - params.yaml
    outs:
      - artifacts/models/best_model.pkl

  model_evaluation:
    cmd: python -m src.model_evaluation
    deps:
      - src/model_evaluation.py
      - artifacts/models/best_model.pkl
      - data/processed/test.npy
    metrics:
      - artifacts/reports/metrics.json:
          cache: false
  
  model_pusher:
      cmd: python -m src.model_pusher
      deps:
        - src/model_pusher.py           # Script khud
        - artifacts/models/best_model.pkl # Naya trained model
        - artifacts/reports/metrics.json  # Naye model ki metrics
        - data/processed/test.npy        # S3 model ko test karne ke liye data
        - params.yaml