data_ingestion:
  test_size: 0.2
  random_state: 42

model_trainer:
  model_name: "logistic regression"

  param_grid:
    C: [0.01, 0.1, 1, 10, 100]
    penalty: ["l1", "l2"]
    solver: ["liblinear"]
    max_iter: [100, 200]